services:
  ms-reservas:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: reservas-ms-reservas:dev
    container_name: reservas-dev-ms-reservas
    restart: unless-stopped
    environment:
      SERVER_PORT: 8081
      SPRING_DATASOURCE_URL: jdbc:postgresql://reservas-dev-postgres:5432/reservasdb_dev
      SPRING_DATASOURCE_USERNAME: reservas
      SPRING_DATASOURCE_PASSWORD: reservas123
      JPA_HIBERNATE_DDL_AUTO: update
      SHOW_SQL: true
    ports:
      - "8092:8081"
    networks:
      reservas-dev-net:
        aliases:
          - ms-reservas

networks:
  reservas-dev-net:
    external: true
    name: reservas-dev-net
