server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: ms-reservas
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/reservasdb}
    username: ${SPRING_DATASOURCE_USERNAME:reservas}
    password: ${SPRING_DATASOURCE_PASSWORD:reservas123}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SHOW_SQL:true}
    open-in-view: false